apiVersion: v1
kind: Service
metadata:
  name: model-manager-nodeport
  namespace: model-hosting
  labels:
    app: model-manager
    release: model-manager
spec:
  type: NodePort
  selector:
    app: model-manager
    release: model-manager
  ports:
    - name: http
      port: 30501
      targetPort: 8080
      nodePort: 30501
      protocol: TCP
